mindmap
  root(("赣锋锂业<br/>全球资源布局<br/>3640万吨LCE"))
    澳大利亚
      Mount Marion
        产能90万吨/年
      Pilgangoora
        参股项目
      Mt Cattlin
        锂辉石矿
    阿根廷
      Mariana盐湖
        一期2万吨氯化锂已投产
      Cauchari-Olaroz
        2024年产出约2万吨碳酸锂
      Incahuasi
      Sal de la Puna
    中国
      青海盐湖
        吸附法提锂
      江西宜春
        锂云母
      内蒙古镶黄旗
        磷酸铁锂项目
    其他地区
      马里
      墨西哥
      爱尔兰
      非洲
